// <auto-generated />
namespace EventCaveWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedEventRelationsToUser_AddedAttendeesToEvent_AddedCategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedEventRelationsToUser_AddedAttendeesToEvent_AddedCategories));
        
        string IMigrationMetadata.Id
        {
            get { return "201911221503335_AddedEventRelationsToUser_AddedAttendeesToEvent_AddedCategories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
